### ISSUE TITLE
Can't run multiple instances

### ISSUE THREAD

**Issue by siliconalchemy** [arioch/puppet-redis#78] opened 2016-01-06 22:39 UTC
With redis-cluster it looks like it's a common use pattern to invoke multiple instances of redis on the same server, do this on multiple servers, and let redis-trib distribute the masters and slaves across these instances.  
But this puppet module is a singleton class so can't be invoked more than once (unless I've misunderstood, which is entirely possible), perhaps it can be altered to work as a parameterised defined type instead so multiple instances can be invoked - and you get the benefits of hiera etc baked in as well.
This is a bit of a showstopper with cluster.

**Comment by vide** [comment] 2016-05-12 07:11
Yeah @siliconalchemy you got it right, this module only support ONE instance of puppet per server, and it's a pity because redis is heavily used in multi-instances environments. Moreover this module is not that easy to fork and adapt, as it's heavily focused on the singleton approach, and given the fact that the author is not that active on it anymore. I guess that we have to find another module

**Comment by petems** [comment] 2016-10-14 23:45
Duplicate of https://github.com/arioch/puppet-redis/issues/113, @spo0nman is working on a multi instance version of the module 👍

**Closed by petems** 2016-10-14 23:45 UTC
